/* Group Number: 7
Hamsini G - 2023A7PS0006P
Neha Gujjari - 2023A7PS0011P
Kushi Arun Kumar - 2023A7PS0546P
Kritika Pandey - 2023A7PS0022P
Laavanya Datta - 2023A7PS0536P*/

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <time.h>
#include "lexer.h"
#include "parser.h"

void runLexer(char *srcFile){
    //Run lexer and print the tokens and errors on console
    initLexer();
    FILE *f= fopen(srcFile, "r");
    if (!f) {
        fprintf(stderr, "Could not open %s\n", srcFile);
        return;
    }
    twinBuffer B;
    initBuffer(&B, f);

    TokenArray tokenStream;
    initTokenArray(&tokenStream);

    int currentLine= 1;
    //Scan until the buffer is exhausted
    while (!lexerDone(&B)) {
        getNextToken(&B, &tokenStream, &currentLine, f);
    }

    //Output on console
    printTokens(&tokenStream);
    printAndFreeErrors();       
    displaySymbolTable();
    freeTokenArray(&tokenStream);
    fclose(f);
}

void lexerToParser(char *srcFile, char *destFile, char *outFile){
    //Run lexer and write the tokens in destFile
    initLexer();
    FILE *f= fopen(srcFile, "r");
    if (!f) {
        fprintf(stderr, "Could not open %s\n", srcFile);
        return;
    }
    FILE *d= fopen(destFile, "w");
    if (!d) {
        fprintf(stderr, "Could not open %s\n", destFile);
        return;
    }
    twinBuffer B;
    initBuffer(&B, f);
    TokenArray tokenStream;
    initTokenArray(&tokenStream);
    int currentLine= 1;
    while (!lexerDone(&B)) {
        getNextToken(&B, &tokenStream, &currentLine, f);
    }
    printAndFreeErrors();
    printTokensToFile(d, tokenStream.data, tokenStream.size);  
    freeTokenArray(&tokenStream);
    fclose(d);

    //Load grammar, create first and follow sets, create parse table and errorlist
    Grammar *g= (Grammar*) malloc(sizeof(Grammar));
    loadGrammar(g);
    int **first= NULL; 
    int **follow= NULL;
    computeFirstAndFollow(g, &first, &follow);
    int *table= NULL;
    createParseTable(g, &first, &follow, &table);
    ErrorList* errorList= (ErrorList*) calloc(1, sizeof(ErrorList));
    //Run parser on destFile created by lexer
    ParseTreeNode *root= parseSourceCode(destFile, g, table, errorList);
    printParseTree(root, outFile);
    //Free memory
    freeParseTree(root);
    free(table);
    free(errorList);
}

void checkTime(char *srcFile, char *destFile, char *outFile) {
    clock_t start_time, end_time;
    double total_CPU_time, total_CPU_time_in_seconds;

    start_time= clock();
    lexerToParser(srcFile, destFile, outFile);
    end_time= clock();
    total_CPU_time= (double) (end_time-start_time);
    total_CPU_time_in_seconds= total_CPU_time/CLOCKS_PER_SEC;

    printf("Total CPU time: %lf\n", total_CPU_time);
    printf("Total CPU time in seconds: %lf\n", total_CPU_time_in_seconds);
}

int main(int argc, char *argv[]) {
    int option= 0;
    char *destFile= "dest.txt";

    if (argc< 3) {
        printf("Usage: %s <source_file> <output_file>\n", argv[0]);
        return 1;
    }

    char *srcFile= argv[1];
    char *outFile= argv[2];

    while(1) {
        printf("Enter option :\n0 : Exit\n1 : Remove comments\n2 : Print the token list (on the console) generated by the lexer\n3 : Parsing the input source code and print the parse tree to the output filey\n4 : Print the total time (on the console) taken by the lexer and parser to verify the syntactic correctness\n");
        scanf("%d", &option);
        if(option== 0) {
            return 0;
        } else if(option== 1) {
            removeComments(srcFile);
        } else if(option== 2) {
            runLexer(srcFile);
        } else if(option== 3) {
            lexerToParser(srcFile, destFile, outFile);
        } else if(option== 4) {
            checkTime(srcFile, destFile, outFile);
        } else{
            printf("Invalid input\n");
        }
    }

    return 0;
}